[project]
name = "nulls-studio"
version = "0.1.0"
description = "A modding tool for Null's Brawl, written in Flet."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "flet>=0.86.2",
    "flet-code-editor>=0.86.2",
    "flet-permission-handler>=0.86.2",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "pyjnius>=1.7.0",
]

[dependency-groups]
dev = [
    "basedpyright>=1.39.9",
    "flet[all]>=0.86.2",
    "mypy>=2.3.0",
    "ruff>=0.16.0",
]


# Tools setup
[tool.ruff]
line-length = 80
target-version = "py314"

[tool.ruff.lint]
select = ["E", "F", "I", "UP", "B", "SIM"]

[tool.mypy]
python_version = "3.14"
strict = true

[tool.basedpyright]
venvPath = "."
venv = ".venv"

[[tool.basedpyright.executionEnvironments]]
root = "."
reportUnknownMemberType = "none"
reportExplicitAny = "none"
